[package]
name = "kodik-parser"
version = "0.4.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
regex = { version = "1.11.1" }
reqwest = { version = "0.12.22", default-features = false, features = [
    "json",
    "default-tls",
] }
serde = { version = "1.0.219", default-features = false, features = [
    "serde_derive",
] }
ua_generator = { version = "0.5.20", default-features = false }

[dev-dependencies]
tokio = { version = "1.47.1", default-features = false, features = ["macros"] }
